# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/学习有关/nscscc文档/nscscc2018_release_v0.03/func_test_v0.02/soc_axi_func/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
# IP: The module: 'axi_crossbar_1x2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/学习有关/nscscc文档/nscscc2018_release_v0.03/func_test_v0.02/soc_axi_func/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_crossbar_1x2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/学习有关/nscscc文档/nscscc2018_release_v0.03/func_test_v0.02/soc_axi_func/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
# IP: The module: 'axi_crossbar_1x2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/学习有关/nscscc文档/nscscc2018_release_v0.03/func_test_v0.02/soc_axi_func/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_crossbar_1x2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
